// src/components/blog/PostListing.vue
<template lang="pug">
    div.container
        post-preview.item(v-for="post in posts" :key="post.slug" :data="post")
</template>

<script>
import PostPreview from '~/components/blog/PostPreview'

export default {
    components: {
        'post-preview': PostPreview,
    },
    props: ['posts'],
}
</script>

<style lang="scss" scoped>
.container {
    margin-top: 3em;
    margin-bottom: 3em;
}

.item {
    margin: 1em;
}
</style>

// src/lib/components/blog/PostListing.svelte
<script lang="ts">
  import PostPreview from '$lib/components/blog/PostPreview.svelte'
  import type { Post } from '$lib/types'

  export let posts: Post[]
</script>

<div class="container">
  <ul>
    {#each posts as post}
      <li>
        <PostPreview {post} />
      </li>
    {/each}
  </ul>
</div>

<style lang="scss">
  .container {
    margin-top: 3em;
    margin-bottom: 3em;
  }

  li {
    margin-bottom: 1em;
  }
</style>
